name: app
description: "A new church app."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.12.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.4.0
  cloud_firestore: ^4.17.0
  firebase_pagination: ^3.1.0
  awesome_dialog: ^3.2.0
  flutter_iconly: ^1.0.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  mpesadaraja: ^0.1.5
  http: ^0.13.6
  firebase_storage: ^11.7.7
  mockito: ^5.4.4
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4
  web_socket_channel: ^3.0.0
  pay_with_paystack: ^1.0.4
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  webview_universal: ^0.0.5
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/HOME2.png
    # - assets/images/home.png
    # - assets/images/HotelMS.png
    # - images/
    # - assets/images/
    # - assets/carousel/
    # - .env
    
  fonts:
    - family: Arimo
      fonts:
        - asset: /fonts/Arimo-Regular.ttf
        - asset: /fonts/Arimo-Italic.ttf
        - asset: /fonts/Arimo-Bold.ttf
        - asset: /fonts/Arimo-BoldItalic.ttf
    - family: Poppins
      fonts:
        - asset: /fonts/Poppins-SemiBold.ttf
        - asset: /fonts/Poppins-Bold.ttf
        - asset: /fonts/Poppins-ExtraBold.ttf
        - asset: /fonts/Poppins-ExtraLight.ttf
        - asset: /fonts/Poppins-Light.ttf
        - asset: /fonts/Poppins-Medium.ttf
        - asset: /fonts/Poppins-SemiBoldItalic.ttf
        - asset: /fonts/Poppins-BoldItalic.ttf
        - asset: /fonts/Poppins-ExtraBoldItalic.ttf
        - asset: /fonts/Poppins-ExtraLightItalic.ttf
        - asset: /fonts/Poppins-LightItalic.ttf
        - asset: /fonts/Poppins-MediumItalic.ttf
        - asset: /fonts/Poppins-Italic.ttf
        - asset: /fonts/Poppins-Regular.ttf



   